### ISSUE TITLE
Best practice for adding a modified monomer

### ISSUE THREAD

**Issue by pamelarussell** [PistoiaHELM/HELM2NotationToolkit#10]
Hi,

I am trying to use `org.helm.notation2.tools.SequenceConverter.getNucleotideSequenceFromNotation()` with a new monomer, e.g. `[m5c]` in `"RNA1{R(U)P.R(T)P.R(G)P.R(C)P.R([m5C])}$$$$V2.0"`.

I am currently pointing to the bundled monomer DB in the .jar file. What is the best way to add new modified bases as well as sugars and 3' phosphates?

Here is my `~/.helm/MonomerStoreConfig.properties`:

```
update.automatic=true
use.webservice=false
use.external.monomers=false
external.monomers.path=null
use.external.nucleotides=false
use.external.attachments=false
```

This is the stack trace when the monomer is not found in the bundled database:

```
org.helm.notation2.exception.MonomerException: Defined Monomer is not in the database and also not valid SMILES m5C
	at org.helm.notation2.tools.MethodsMonomerUtils.getMonomer(MethodsMonomerUtils.java:237)
	at org.helm.notation2.tools.NucleotideParser.convertToNucleotide(NucleotideParser.java:321)
	at org.helm.notation2.tools.RNAUtils.getNucleotideList(RNAUtils.java:869)
	at org.helm.notation2.tools.RNAUtils.getNucleotideSequence(RNAUtils.java:802)
	at org.helm.notation2.tools.SequenceConverter.getNucleotideSequenceFromNotation(SequenceConverter.java:125)
        ...
```

Thanks!

**Comment by ClairePA** [comment]
You can use the HELM2MonomerService API to add update and delete monomers. See http://webeditor.openhelm.org/HELM2MonomerService/ for the call details. You need to define the monomer in this format:
`{
  "symbol": "A",
  "name": "Adenine",
  "molfile": "HELM Core Monomer library\n  Ketcher 10131612512D 1   1.00000     0.00000     0\n\n 11 12  0     0  0            999 V2000\n    0.9632   -3.5449    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0970   -4.0450    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0970   -5.0451    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.9630   -5.5451    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8291   -5.0452    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8293   -4.0451    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.8536   -5.3539    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.4413   -4.5449    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.8535   -3.7357    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    0.9632   -2.5448    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.1626   -6.3051    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1 10  1  0     0  0\n  1  6  2  0     0  0\n  1  2  1  0     0  0\n  9  2  1  0     0  0\n  2  3  2  0     0  0\n  7  3  1  0     0  0\n  3  4  1  0     0  0\n  4  5  2  0     0  0\n  5  6  1  0     0  0\n  7  8  1  0     0  0\n  7 11  1  0     0  0\n  8  9  2  0     0  0\nA   11\nR1\nM  END\n",
  "author": "Pistoia Alliance HELM project",
  "id": 1516,
  "rgroups": [
    {
      "id": 0,
      "alternateId": "R1-H",
      "label": "R1",
      "capGroupName": "H",
      "capGroupSMILES": "[*:1][H]"
    }
  ],
  "createDate": null,
  "polymerType": "RNA",
  "naturalAnalog": "A",
  "smiles": "[H:1]n1cnc2c(N)ncnc21",
  "monomerType": "Branch"
}`

**Comment by pamelarussell** [comment]
Thank you! I'm not using a web service and instead need to use a local monomer database. I believe this concerns the `use.external.monomers` and `external.monomers.path` options in `~/.helm/MonomerStoreConfig.properties`. What is the workflow to correctly add monomers to a static database and point the code to it?

**Comment by nh13** [comment]
@ClairePA we would like to the toolkit API in a Java/Scala code directly, versus having to have a web service API.  Is there a javadoc equivalent you could point us to for that API call?  And how to add monomers to the database before running the java API?

**Comment by ClairePA** [comment]
Hi @nh13. Some details below from quattro research who wrote the toolkit.  

The JavaDoc can be found on the Nexus repository: https://oss.sonatype.org/service/local/repositories/releases/archive/org/pistoiaalliance/helm/helm2-notationtoolkit/1.3.10/helm2-notationtoolkit-1.3.10-javadoc.jar/!/index.html
There is no need to run the web service to work with the monomers.
![temp](https://user-images.githubusercontent.com/3986896/136379307-6122262d-2d5f-4358-b273-1c15ec5e20ce.png)

**Comment by nh13** [comment]
@ClairePA thanks for the link, that is super helpful.  Any thoughts on [Pam's](https://github.com/PistoiaHELM/HELM2NotationToolkit/issues/10#issuecomment-915222341) question?
