### ISSUE TITLE
Using local monomer DB: "Unable to use local monomer DB file"

### ISSUE THREAD

**Issue by pamelarussell** [PistoiaHELM/HELM2NotationToolkit#9]
Hi,

I am trying to wrap methods in `HELM2NotationToolkit` for simple conversion between nucleotide sequences and HELM2 notation (in Scala). I would like to run locally without pinging the REST API. I am having trouble configuring the monomer cache to use a local database. Below I describe what I've tried, but I'm hoping there is a simpler way to point to the monomer database that ships with the .jar file rather than the manual configuration with a local copy of the database that I'm attempting currently.

Here is my wrapper code:

```
import org.helm.notation2.parser.ParserHELM2
import org.helm.notation2.parser.notation.HELM2Notation
import org.helm.notation2.tools.SequenceConverter

object HelmNotation {

  def nucleotideToHelm2(seq: String): Unit = {
    SequenceConverter.readRNA(seq)
  }

  def helmToNucleotide(helm2: HELM2Notation): String = {
    SequenceConverter.getNucleotideSequenceFromNotation(helm2)
  }

  def helmToNucleotide(helm2: String): String = {
    val parser = new ParserHELM2()
    parser.parse(helm2)
    val helm2Notation = parser.getHELM2Notation
    this.helmToNucleotide(helm2Notation)
  }

}
```

Here is what I'm currently doing to configure the monomer DB:

I've made a `~/.helm/MonomerStoreConfig.properties` attempting to point to the monomer database in `MonomerDBGZEncoded.xml` as follows (local file path removed):

```
use.webservice=false
update.automatic=true
use.external.monomers=true
use.external.nucleotides=true
use.external.attachments=true
external.monomers.path=/path/to/MonomerDBGZEncoded.xml
external.nucleotides.path=xyz
external.attachments.path=xyz
```

When invoking my function `nucleotideToHelm2()`, I am getting stuck when the code tries to use the local monomer DB file.

Is there a simpler way to run this locally? Thank you!!

```
Aug 31, 2021 5:21:08 AM org.helm.notation2.NucleotideFactory initalizeNucleotideTemplatesFromExternalFile
INFO: resources/NucleotideTemplates.xml is used for nucleotide templates initialization
Aug 31, 2021 5:21:08 AM org.helm.notation2.MonomerFactory initializeMonomerCache
INFO: Unable to use local monomer DB file: /path/to/MonomerDBGZEncoded.xml


Cannot invoke "org.helm.notation2.MonomerCache.getMonomerDB()" because "cache" is null
java.lang.NullPointerException: Cannot invoke "org.helm.notation2.MonomerCache.getMonomerDB()" because "cache" is null
	at org.helm.notation2.MonomerFactory.initializeMonomerCache(MonomerFactory.java:747)
	at org.helm.notation2.MonomerFactory.refreshMonomerCache(MonomerFactory.java:299)
	at org.helm.notation2.MonomerFactory.getInstance(MonomerFactory.java:288)
	at org.helm.notation2.tools.FastaFormat.initMapNucleotidesNaturalAnalog(FastaFormat.java:260)
	at org.helm.notation2.tools.FastaFormat.generateElementsforRNA(FastaFormat.java:343)
	at org.helm.notation2.tools.SequenceConverter.readRNA(SequenceConverter.java:100)
	at com.....util.HelmNotation$.nucleotideToHelm2(HelmNotation.scala:10)
	at com.....util.HelmNotationTest.$anonfun$new$1(HelmNotationTest.scala:8)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1308)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1308)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1474)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

**Comment by TianhongZhang** [comment]
Can you try to set the value of external.monomers.path to xyz so that it will not found it and force the use of the bundled 
MonomerDBGZEncoded.xml file in the project or jar file? (Not sure if you are using the jar from the project or the project directly). From the trace, it seems that it found the bundled NucleotideTemplates.xml successfully.  Good luck!

**Comment by TianhongZhang** [comment]
Took a look at the source code of MonomerFactory.java class, you can simply set
use.external.monomers=false
to force the use of the bundled monomer db file.

**Comment by pamelarussell** [comment]
`use.external.monomers=false` is working for me; thanks!
